packages:
  - apps/*
  - packages/*
injectWorkspacePackages: true
allowBuilds:
  '@scarf/scarf': false
  cpu-features: false
  esbuild: true
  msgpackr-extract: true
  protobufjs: false
  ssh2: false
  unrs-resolver: true
